[profile.default]
src = "src"
out = "out"  
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.optimizer_details]
yul = true